name: Windows

on:
  push:
   # tirgger on pushes to main branch except when only documentation is changed
    branches:
      - master
    paths-ignore:
      - '**.md'
   

jobs:

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create and push tag if it doesn't exist
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        echo "Pushing tag $(git rev-parse --short HEAD)"
        git tag $(git rev-parse --short HEAD)
        git push origin $(git rev-parse --short HEAD)
    - name: setup
      run: |
        cd ../..
        git clone https://github.com/open-ephys/plugin-GUI.git --branch main
        cd plugin-GUI/Build
        cmake -G "Visual Studio 17 2022" -A x64 .. 
        mkdir Release && cd Release
        curl -L https://openephys.jfrog.io/artifactory/GUI-binaries/Libraries/open-ephys-lib-v1.0.0.zip --output open-ephys-lib.zip
        unzip open-ephys-lib.zip
      shell: bash
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: configure
      run: |
        cd Build
        cmake -G "Visual Studio 17 2022" -A x64 .. 
      shell: bash
    - name: build
      run: |
        msbuild Build/INSTALL.vcxproj -p:Configuration=Release -p:Platform=x64
      shell: cmd
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: Build/Release/open-ephys-plugin-bonsai.dll 
        tag: $(git rev-parse --short HEAD)